### ISSUE TITLE
Problem install with Xcode10.1 in HighSierra

### ISSUE THREAD

**Issue by muizidn** [SvenTiigi/homebrew-swiftkit#1]
I'm trying to install from homebrew. My machine configuration is macOS HighSierra with Xcode 10.1 (Swift 4.2.1) but to no avail.

Then I try to use Swift 5.0.1-RELEASE toolchain by manually build it. It succeeds. Am I missing something?

**Comment by SvenTiigi** [comment]
Hey @muizidn,

brew will run the following command when installing `SwiftKit`

```bash
system "swift", "build", "--disable-sandbox", "-c", "release"
```

As `SwiftKit` is written in Swift `5.0` a Xcode Toolchain Version >= `10.2.0` is needed which contains the Swift `5.0` runtime in order to successfully build the `SwiftKit` executable.

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.
